# Zero2LLMV 测试训练实验配置
# 用于验证SwanLab监控集成

model:
  model_type: "llm"              # 使用LLM模式进行快速测试
  model_config_path: ""

data:
  data_path: "data/test"         # 测试数据路径
  max_seq_length: 128            # 较短序列长度，加快训练
  batch_size: 2                  # 小批量大小，适合测试
  num_workers: 1

training:
  num_epochs: 2                  # 只训练2个epoch用于测试
  learning_rate: 5e-4            # 稍高的学习率，便于观察变化
  weight_decay: 0.01
  warmup_steps: 10               # 少量warmup步骤
  gradient_accumulation_steps: 2  # 梯度累积
  max_grad_norm: 1.0
  use_amp: false                 # 禁用混合精度，简化测试

checkpoints:
  output_dir: "./test_outputs"   # 测试输出目录
  save_steps: 50                 # 频繁保存检查点用于测试
  logging_steps: 5               # 频繁记录日志
  eval_steps: 20

swanlab:
  project: "VLLM"                    # SwanLab项目名
  workspace: "testworkspace"         # 工作空间
  experiment_name: "test-integration"  # 测试实验名
  description: "测试SwanLab监控集成的简单实验"  
  logdir: "./swanlab_logs"

  # 本地日志目录

  #class TrainingConfig:
  #    """训练配置类"""
  #    # 模型配置
  #    model_type: str = "vlm"  # 模型类型: "llm" or "vlm"
  #    model_config_path: str = ""  # 模型配置文件路径
  #
  #    # 数据配置
  #    data_path: str = "data/processed"  # 训练数据路径
  #    max_seq_length: int = 512  # 最大序列长度
  #    batch_size: int = 8  # 批次大小
  #    num_workers: int = 4  # 数据加载器线程数
  #
  #    # 训练配置
  #    num_epochs: int = 3  # 训练轮数
  #    learning_rate: float = 2e-5  # 学习率
  #    weight_decay: float = 0.01  # 权重衰减
  #    warmup_steps: int = 500  # 预热步数
  #    gradient_accumulation_steps: int = 4  # 梯度累积步数
  #    max_grad_norm: float = 1.0  # 梯度裁剪阈值
  #
  #    # 混合精度训练
  #    use_amp: bool = True  # 是否使用自动混合精度
  #
  #    # 保存与日志
  #    output_dir: str = "outputs"  # 输出目录
  #    save_steps: int = 1000  # 保存检查点的步数间隔
  #    logging_steps: int = 100  # 日志记录的步数间隔
  #    eval_steps: int = 500  # 评估的步数间隔
  #
  #    # SwanLab配置
  #    swanlab_project: str = "VLLM"  # swanlab项目名
  #    swanlab_workspace: str = "delahayecarry"  # swanlab工作空间
  #    swanlab_experiment_name: str = ""  # 实验名称
  #    swanlab_description: str = ""  # 实验描述
  #    swanlab_logdir: str = ""  # 日志目录
  #
  #    # SwanLab API配置
  #    swanlab_api_key: str = ""  # API密钥