# zerollm-v VLM训练配置
# 与pydantic模型兼容的配置文件

model:
  model_type: "vlm"
  model_config_path: ""

data:
  data_path: "../dataset/pretrain_data.jsonl"
  max_seq_length: 640
  batch_size: 16
  num_workers: 8

training:
  num_epochs: 4
  learning_rate: 4e-4
  weight_decay: 0.01
  warmup_steps: 0
  gradient_accumulation_steps: 1
  max_grad_norm: 1.0
  use_amp: true

checkpoints:
  output_dir: "../out"
  save_steps: 200
  logging_steps: 50
  eval_steps: 500

swanlab:
  project: "zerollm-v"
  workspace: "delahayecarry"
  experiment_name: "vlm-pretrain"
  description: "zerollm-v VLM预训练实验 - 支持图像理解的多模态大语言模型"
  logdir: "./swanlab_logs"